[build]
  command = "npm run build"
  publish = "public/build"  # This is the default Remix output directory

[dev]
  command = "npm run dev"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"
